apiVersion: v1
kind: ConfigMap
metadata:
  name: talend-job-config
  namespace: talend-jobs
data:
  user: "some_user"
  host: "some.example.com"
  port: "8000"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: print-context
  namespace: talend-jobs
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: print-context
              image: print-context:latest
              imagePullPolicy: Never
              env:
                - name: CONTEXT_user
                  valueFrom:
                    configMapKeyRef:
                      name: talend-job-config
                      key: user
                - name: CONTEXT_password
                  valueFrom:
                    secretKeyRef:
                      name: talend-job-secrets
                      key: password
          restartPolicy: OnFailure
  schedule: "0 * * * *"