#!/bin/sh -e
# This is a wrapper script around the run script generated by talend. This allows for converting environment variables
# to context parameters. There are two methods and you probably only want to use one of them (or neither).

SELF=$(basename "${0}")

# Only run if a context file was specified.
if [ -n "${CONTEXT}" ]; then
  echo "${SELF}: Running env-to-props"
  ./env-to-props "${CONTEXT}"
fi

cd JOB_NAME

if ! grep -q exec JOB_NAME_run.sh; then
  echo "${SELF}: WARN: shell script should have \"exec java ...\" for proper signal handling"
  echo "${SELF}: See https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example"
fi

# Only run if the shell scripts exists and is executable.
if [ -x ../env-to-context-param.sh ]; then
  echo "${SELF}: Running env-to-context-param.sh"
  ../env-to-context-param.sh ./JOB_NAME_run.sh "$@"
else
  echo "${SELF}: Running JOB_NAME_run.sh"
  exec ./JOB_NAME_run.sh "$@"
fi

# Change JOB_NAME so it is obvious it is getting replaced, like @JOB_NAME@ ?
# Change so only one context thing happens.