#!/bin/sh -e
# This is a wrapper script around the run script generated by talend. This allows for converting environment variables
# to context parameters. There are two methods and you probably only want to use one of them (or neither).

# Only run if a context file was specified.
if [ -n "${CONTEXT}" ]; then
  ./env-to-props "${CONTEXT}"
fi

cd JOB_NAME

if ! grep -q exec JOB_NAME_run.sh; then
  echo "WARN: shell script should have \"exec java ...\" for proper signal handling"
  echo "See https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example"
fi

# Only run if the shell scripts exists and is executable.
if [ -x ../env-to-context-param.sh ]; then
  ../env-to-context-param.sh ./JOB_NAME_run.sh "$@"
else
  exec ./JOB_NAME_run.sh "$@"
fi
